AWSTemplateFormatVersion: '2010-09-09'
Description: 'Nested Stack for Amplify App'

Parameters:
  ApiEndpoint:
    Type: String
    Description: API Gateway endpoint URL
    
  KMSKeyArn:
    Type: String
    Description: KMS Key ARN for encryption
    Default: ''

Conditions:
  HasKMSKey: !Not [!Equals [!Ref KMSKeyArn, '']]

Resources:
  # CloudWatch Log Group for Amplify Build Logs
  AmplifyLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: '/aws/amplify/hotel-booking-app'
      RetentionInDays: 30
      KmsKeyId: !If [HasKMSKey, !Ref KMSKeyArn, !Ref 'AWS::NoValue']
  # Secure Amplify App
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: hotel-booking-app
      Description: Secure Hotel Booking Application
      BuildSpec: |-
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci --only=production
                - npm audit --audit-level high
            build:
              commands:
                - npm run build
                - npm run test:security
          artifacts:
            baseDirectory: build
            files:
              - '**/*'
          cache:
            paths:
              - node_modules/**/*
      CustomRules:
        - Source: '/<*>'
          Target: '/index.html'
          Status: '404-200'
        - Source: '/api/<*>'
          Target: !Ref ApiEndpoint
          Status: '200'
          Condition: '<US>'
      EnvironmentVariables:
        - Name: REACT_APP_API_URL
          Value: !Ref ApiEndpoint
        - Name: NODE_ENV
          Value: production
        - Name: GENERATE_SOURCEMAP
          Value: 'false'
      Tags:
        - Key: Environment
          Value: Production
        - Key: SecurityLevel
          Value: Enterprise
        - Key: Application
          Value: AB3-HotelBooking

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: main
      EnableAutoBuild: true
      EnablePullRequestPreview: false
      Stage: PRODUCTION
      Framework: React
      EnvironmentVariables:
        - Name: AMPLIFY_DIFF_DEPLOY
          Value: 'false'
        - Name: AMPLIFY_MONOREPO_APP_ROOT
          Value: amplify-app
      Tags:
        - Key: Environment
          Value: Production
        - Key: Branch
          Value: main

  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmplifyMinimalAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - amplify:GetApp
                  - amplify:GetBranch
                  - amplify:ListBranches
                  - amplify:GetJob
                  - amplify:ListJobs
                  - amplify:StartJob
                  - amplify:StopJob
                  - amplify:GetWebhook
                  - amplify:ListWebhooks
                  - amplify:CreateDeployment
                  - amplify:GetDeployment
                  - amplify:ListDeployments
                Resource:
                  - !Sub 'arn:aws:amplify:${AWS::Region}:${AWS::AccountId}:apps/*'
              - Effect: Allow
                Action:
                  - codecommit:GetRepository
                  - codecommit:ListBranches
                  - codecommit:ListRepositories
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetDifferences
                  - codecommit:GetReferences
                  - codecommit:ListTagsForResource
                Resource:
                  - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:DeleteObject
                  - s3:ListBucket
                  - s3:GetBucketLocation
                Resource:
                  - 'arn:aws:s3:::amplify-*'
                  - 'arn:aws:s3:::amplify-*/*'
                  - !Sub 'arn:aws:s3:::amplify-${AmplifyApp}-*/*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/amplify/*'

Outputs:
  AmplifyAppURL:
    Description: "Amplify App URL"
    Value: !Sub "https://${AmplifyBranch.BranchName}.${AmplifyApp.DefaultDomain}"
  
  AmplifyAppId:
    Description: "Amplify App ID"
    Value: !GetAtt AmplifyApp.AppId
  
  AmplifyBranchName:
    Description: "Amplify Branch Name"
    Value: !Ref AmplifyBranch