AWSTemplateFormatVersion: '2010-09-09'
Description: 'Secure Nested Stack for Glue ETL Jobs'

Parameters:
  XRayDataBucketName:
    Type: String
    Description: Name of the S3 bucket for X-Ray data
    
  KMSKeyArn:
    Type: String
    Description: KMS Key ARN for encryption
    
  VPCId:
    Type: String
    Description: VPC ID for Glue jobs
    
  PrivateSubnet1Id:
    Type: String
    Description: Private subnet 1 ID
    
  PrivateSubnet2Id:
    Type: String
    Description: Private subnet 2 ID

Resources:
  # KMS Key for Glue Encryption (if not passed from parent)
  GlueKMSKey:
    Type: AWS::KMS::Key
    Condition: CreateKMSKey
    Properties:
      Description: KMS Key for Glue ETL encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow Glue Service
            Effect: Allow
            Principal:
              AWS: !GetAtt GlueServiceRole.Arn
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
            Resource: '*'

  GlueKMSKeyAlias:
    Type: AWS::KMS::Alias
    Condition: CreateKMSKey
    Properties:
      AliasName: alias/ab3-glue-encryption
      TargetKeyId: !Ref GlueKMSKey

  # Secure S3 Bucket for Glue Data
  GlueDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-glue-data-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !If [CreateKMSKey, !Ref GlueKMSKey, !Ref KMSKeyArn]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: glue-data-access/

  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-glue-access-logs-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  GlueDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref GlueDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${GlueDataBucket.Arn}/*'
              - !GetAtt GlueDataBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: AllowGlueAccess
            Effect: Allow
            Principal:
              AWS: !GetAtt GlueServiceRole.Arn
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
            Resource:
              - !Sub '${GlueDataBucket.Arn}/*'
              - !GetAtt GlueDataBucket.Arn

  # Glue Security Configuration
  GlueSecurityConfiguration:
    Type: AWS::Glue::SecurityConfiguration
    Properties:
      Name: AB3-Glue-Security-Config
      EncryptionConfiguration:
        S3Encryptions:
          - S3EncryptionMode: SSE-KMS
            KmsKeyArn: !If [CreateKMSKey, !GetAtt GlueKMSKey.Arn, !Ref KMSKeyArn]
        CloudWatchEncryption:
          CloudWatchEncryptionMode: SSE-KMS
          KmsKeyArn: !If [CreateKMSKey, !GetAtt GlueKMSKey.Arn, !Ref KMSKeyArn]
        JobBookmarksEncryption:
          JobBookmarksEncryptionMode: CSE-KMS
          KmsKeyArn: !If [CreateKMSKey, !GetAtt GlueKMSKey.Arn, !Ref KMSKeyArn]

  # Glue Security Group
  GlueSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Glue jobs with minimal access
      VpcId: !Ref VPCId
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS outbound for AWS API calls only
      Tags:
        - Key: Name
          Value: AB3-Glue-SG

  # Glue Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: ab3_trace_database
        Description: Secure database for AB3 trace data

  # Secure IAM Role for Glue
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: GlueS3AccessMinimal
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${XRayDataBucketName}/xray-data/*'
                  - !Sub 'arn:aws:s3:::${XRayDataBucketName}'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub '${GlueDataBucket.Arn}/processed-data/*'
                  - !Sub '${GlueDataBucket.Arn}/temp/*'
                  - !Sub '${GlueDataBucket.Arn}/scripts/*'
                  - !GetAtt GlueDataBucket.Arn
        - PolicyName: GlueKMSAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !If [CreateKMSKey, !GetAtt GlueKMSKey.Arn, !Ref KMSKeyArn]

  # Secure Glue Jobs
  PrepTraceDataJob:
    Type: AWS::Glue::Job
    Properties:
      Name: Prep-Trace-Data-for-TCO_TBM
      Role: !GetAtt GlueServiceRole.Arn
      SecurityConfiguration: !Ref GlueSecurityConfiguration
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${GlueDataBucket}/scripts/prep_trace_data.py'
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': !Sub 's3://${GlueDataBucket}/temp/'
        '--enable-metrics': ''
        '--enable-continuous-cloudwatch-log': 'true'
      MaxRetries: 0
      GlueVersion: '3.0'
      NumberOfWorkers: 2
      WorkerType: 'G.1X'
      Timeout: 60

  ETLFinalWithAthenaJob:
    Type: AWS::Glue::Job
    Properties:
      Name: ETL-Final-With-Athena-Only
      Role: !GetAtt GlueServiceRole.Arn
      SecurityConfiguration: !Ref GlueSecurityConfiguration
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${GlueDataBucket}/scripts/etl_final_with_athena.py'
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': !Sub 's3://${GlueDataBucket}/temp/'
        '--enable-metrics': ''
        '--enable-continuous-cloudwatch-log': 'true'
      MaxRetries: 0
      GlueVersion: '3.0'
      NumberOfWorkers: 2
      WorkerType: 'G.1X'
      Timeout: 60

  CRSRMSHotelsJob:
    Type: AWS::Glue::Job
    Properties:
      Name: CRS-RMS-and-Hotels
      Role: !GetAtt GlueServiceRole.Arn
      SecurityConfiguration: !Ref GlueSecurityConfiguration
      ExecutionProperty:
        MaxConcurrentRuns: 1
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${GlueDataBucket}/scripts/crs_rms_hotels.py'
      DefaultArguments:
        '--job-language': 'python'
        '--TempDir': !Sub 's3://${GlueDataBucket}/temp/'
        '--enable-metrics': ''
        '--enable-continuous-cloudwatch-log': 'true'
      MaxRetries: 0
      GlueVersion: '3.0'
      NumberOfWorkers: 2
      WorkerType: 'G.1X'
      Timeout: 60

Conditions:
  CreateKMSKey: !Equals [!Ref KMSKeyArn, '']

Outputs:
  GlueDataBucketName:
    Description: "Glue Data S3 Bucket"
    Value: !Ref GlueDataBucket
    
  GlueSecurityConfigurationName:
    Description: "Glue Security Configuration Name"
    Value: !Ref GlueSecurityConfiguration
    
  GlueDatabaseName:
    Description: "Glue Database Name"
    Value: !Ref GlueDatabase
    
  GlueServiceRoleArn:
    Description: "Glue Service Role ARN"
    Value: !GetAtt GlueServiceRole.Arn