AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation template for AB3 Full Stack Application'

Parameters:
  RedshiftMasterUsername:
    Type: String
    Default: admin
    NoEcho: true
    Description: Username for Redshift cluster master user
    
  RedshiftMasterPassword:
    Type: String
    NoEcho: true
    Description: Password for Redshift cluster master user
    MinLength: 8

Resources:
  # S3 Bucket for nested stack templates
  TemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-templates-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: templates-access/

  AccessLogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-main-access-logs-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  TemplatesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TemplatesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${TemplatesBucket.Arn}/*'
              - !GetAtt TemplatesBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  # S3 Buckets for shared resources
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-deployment-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: deployment-access/

  DeploymentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeploymentBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${DeploymentBucket.Arn}/*'
              - !GetAtt DeploymentBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  XRayDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'ab3-xray-data-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: xray-data-access/

  XRayDataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref XRayDataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${XRayDataBucket.Arn}/*'
              - !GetAtt XRayDataBucket.Arn
            Condition:
              Bool:
                'aws:SecureTransport': 'false'

  # Nested Stack for Lambda Functions and API Gateway
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket.DomainName}/lambda-stack.yaml'
      Parameters:
        DeploymentBucketName: !Ref DeploymentBucket
        XRayDataBucketName: !Ref XRayDataBucket

  # Nested Stack for Glue ETL Jobs
  GlueStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket.DomainName}/glue-stack.yaml'
      Parameters:
        XRayDataBucketName: !Ref XRayDataBucket

  # Nested Stack for Redshift Cluster
  RedshiftStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket.DomainName}/redshift-stack.yaml'
      Parameters:
        RedshiftMasterUsername: !Ref RedshiftMasterUsername
        RedshiftMasterPassword: !Ref RedshiftMasterPassword

  # Nested Stack for Amplify App
  AmplifyStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplatesBucket.DomainName}/amplify-stack.yaml'
      Parameters:
        ApiEndpoint: !GetAtt LambdaStack.Outputs.ApiEndpoint

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !GetAtt LambdaStack.Outputs.ApiEndpoint
  
  XRayExtractionFunctionArn:
    Description: "X-Ray Extraction Lambda Function ARN"
    Value: !GetAtt LambdaStack.Outputs.XRayExtractionFunctionArn
  
  HotelTraceGeneratorFunctionArn:
    Description: "Hotel Trace Generator Lambda Function ARN"
    Value: !GetAtt LambdaStack.Outputs.HotelTraceGeneratorFunctionArn
  
  RedshiftClusterEndpoint:
    Description: "Redshift Cluster Endpoint"
    Value: !GetAtt RedshiftStack.Outputs.RedshiftClusterEndpoint
  
  RedshiftClusterPort:
    Description: "Redshift Cluster Port"
    Value: !GetAtt RedshiftStack.Outputs.RedshiftClusterPort
  
  AmplifyAppURL:
    Description: "Amplify App URL"
    Value: !GetAtt AmplifyStack.Outputs.AmplifyAppURL
  
  GlueDataBucketName:
    Description: "Glue Data S3 Bucket"
    Value: !GetAtt GlueStack.Outputs.GlueDataBucketName
  
  XRayDataBucketName:
    Description: "X-Ray Data S3 Bucket"
    Value: !Ref XRayDataBucket